# Generated by Django 4.2.30 on 2026-05-18 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя/Фамилия должны начинаться с заглавной буквы, содержать минимум 2 символа. Допускается дефис.', regex='^[A-ZА-ЯЁ][a-zа-яё-]{1,}$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя/Фамилия должны начинаться с заглавной буквы, содержать минимум 2 символа. Допускается дефис.', regex='^[A-ZА-ЯЁ][a-zа-яё-]{1,}$')], verbose_name='Фамилия'),
        ),
    ]
