services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - media_volume:/app/mediafiles
    depends_on:
      - db
      - redis
    networks:
      - jaa_net

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jaa_net

  redis:
    image: redis:7-alpine
    networks:
      - jaa_net

volumes:
  postgres_data:
  media_volume:

networks:
  jaa_net:
    driver: bridge